### ISSUE TITLE
Change base image

### ISSUE THREAD

**Issue by leiserfg** [j1mc/docker-zola#2]
Why are you using node as base if zola is standalone? 
I managed to build an image of just 38M, check at
https://hub.docker.com/r/leiserfg/zola
I made it by using `dockerize`

**Comment by j1mc** [comment]
Hi - thanks for the note on this. I'll take a look at what I can do to build a smaller docker image. Should have time for it this week.

**Comment by j1mc** [comment]
Hi - thanks again for this suggestion. I've changed the base image to use Alpine, and will be pushing the new layout in just a moment. Here's the difference on the container size between `test-zola` container (based on Alpine) and the current version (based on node):

```
REPOSITORY                   TAG      IMAGE ID       CREATED         SIZE
docker.io/j1mc/test-zola     latest   a02700793a36   6 minutes ago   35.4 MB
docker.io/j1mc/docker-zola   latest   9b5b84932bfd   3 days ago      184 MB
```

In closing this issue I'll be moving the `test-zola` changes to the regular `docker-zola` repo, so everyone will get these updates.
