### ISSUE TITLE
Use Docker Image on Forestry

### ISSUE THREAD

**Issue by DirtyF** [j1mc/docker-zola#7]
👋 Hi,

Given I'm using this image to preview a Zola website on Forestry.io
When I use the following command:

```
zola serve --interface 0.0.0.0 --port 8080 --output-dir public
```

I get the following error:

```
error: Found argument 'zola' which wasn't expected, or isn't valid in this context
```

I don't know anything about Docker, but I was wondering if it was possible to run such a command from within your container.

**Comment by j1mc** [comment]
Hi - apologies for the much delayed reply on this, but were you able to sort-out your issues here?

**Comment by DirtyF** [comment]
Hey @j1mc , no I didn't put any more effort on this since.

**Comment by j1mc** [comment]
Instead of port 8080, can you try using port 1111 instead?

**Comment by DirtyF** [comment]
I'll try that, thanks.
